### PR TITLE
Compile on recent hhvm (after fc57e01)

### LINKED ISSUE #47: pgsql no longer compiles
pgsql no longer compiles against HEAD of hhvm master.

Here's the 1st handful of lines:

/home/rrh/dev/hphp-pgsql/pdo_pgsql.cpp:7:17: error: cannot declare variable ‘HPHP::s_pgsql_driver’ to be of abstract type ‘HPHP::PDOPgSql’
 static PDOPgSql s_pgsql_driver;
                 ^
In file included from /home/rrh/dev/hphp-pgsql/pdo_pgsql.cpp:1:0:
/home/rrh/dev/hphp-pgsql/pdo_pgsql.h:8:7: note:   because the following virtual functions are pure within ‘HPHP::PDOPgSql’:
 class PDOPgSql : public PDODriver {
       ^
In file included from /home/rrh/dev/hphp-pgsql/pdo_pgsql.h:5:0,
                 from /home/rrh/dev/hphp-pgsql/pdo_pgsql.cpp:1:
/usr/local/include/hphp/runtime/ext/pdo_driver.h:235:24: note: 	virtual HPHP::PDOResource* HPHP::PDODriver::createResourceImpl()
   virtual PDOResource* createResourceImpl() = 0;

### PR DESCRIPTION
**Pull request by tlevi**
Attempting to fix the build after HHVM changes have broken it, see how rusty my C++ is...

Along the way I changed some variables to line up with the pdo_mysql implementation for my understanding, so the diff is a bit bigger than strictly necessary; hope that isn't a problem.

Fixes #47

### CODE REVIEW

File: pdo_pgsql_connection.cpp [hunk 1]
```diff
@@ -143,20 +144,20 @@ namespace HPHP {
...
         }
     }
 
     bool PDOPgSqlConnection::closer(){
-        if(m_conn){
-            delete m_conn;
-            m_conn = NULL;
+        if(m_server){
+            delete m_server;
+            m_server = NULL;
```
Comment (mssola) [inline pdo_pgsql_connection.cpp]: while you're at it, change it to nullptr ;-)

File: pdo_pgsql_statement.cpp [hunk 2]
```diff
@@ -34,9 +34,9 @@ namespace HPHP {
             // Do we need a check here maybe to see if we've actually got a cursor or not?
             std::stringstream ss;
             ss << "CLOSE " << m_cursorName;
-            m_conn->exec(ss.str());
+            m_server->exec(ss.str());
         }
-        m_pdoconn = NULL;
+        m_server = NULL;
```
Comment (mssola) [inline pdo_pgsql_statement.cpp]: as before, while you're at it change it to  `nullptr`

**Comment by mssola** [comment]
The patch looks good to me and it works :)
